// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanTheThao.Data;

#nullable disable

namespace SanTheThao.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517153608_FixHash")]
    partial class FixHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SanTheThao.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SanTheThao.Models.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SportTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportTypeId");

                    b.ToTable("Courts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Bóng Đá A1",
                            PricePerHour = 200000m,
                            SportTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Bóng Đá A2",
                            PricePerHour = 200000m,
                            SportTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Bóng Đá B1",
                            PricePerHour = 250000m,
                            SportTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Cầu Lông 1",
                            PricePerHour = 80000m,
                            SportTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Cầu Lông 2",
                            PricePerHour = 80000m,
                            SportTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Bóng Chuyền 1",
                            PricePerHour = 150000m,
                            SportTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Bóng Rổ 1",
                            PricePerHour = 120000m,
                            SportTypeId = 4
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Bóng Rổ 2",
                            PricePerHour = 120000m,
                            SportTypeId = 4
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Pickleball 1",
                            PricePerHour = 100000m,
                            SportTypeId = 5
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Pickleball 2",
                            PricePerHour = 100000m,
                            SportTypeId = 5
                        });
                });

            modelBuilder.Entity("SanTheThao.Models.NewsPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("NewsPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Category = "Cầu lông",
                            Content = "Cầu lông là một trong những môn thể thao phổ biến nhất tại Việt Nam. Chơi cầu lông đều đặn giúp cải thiện sức bền tim mạch, tăng cường phản xạ, giảm stress và đốt cháy calories hiệu quả.",
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Slug = "loi-ich-choi-cau-long",
                            Summary = "Cầu lông không chỉ là môn thể thao vui vẻ mà còn mang lại vô số lợi ích sức khoẻ bạn chưa biết.",
                            Title = "5 lợi ích tuyệt vời của việc chơi cầu lông mỗi ngày"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Category = "Pickleball",
                            Content = "Pickleball là sự kết hợp giữa tennis, bóng bàn và cầu lông. Môn này phù hợp mọi lứa tuổi, dễ học và rất thú vị. Năm 2025, Pickleball đã có mặt tại hầu hết các tỉnh thành lớn ở Việt Nam.",
                            CreatedAt = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Slug = "pickleball-hot-2025",
                            Summary = "Pickleball đang bùng nổ tại Việt Nam với hàng nghìn người chơi mới mỗi tháng. Tìm hiểu ngay!",
                            Title = "Pickleball — Môn thể thao hot nhất 2025 tại Việt Nam"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Category = "Bóng đá",
                            Content = "Có 3 loại giày phổ biến: FG (sân cỏ tự nhiên), AG (sân cỏ nhân tạo) và TF (sân phủi). Tại Việt Nam hầu hết sân mini là cỏ nhân tạo nên chọn giày AG hoặc TF để tránh trơn trượt.",
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Slug = "chon-giay-da-bong",
                            Summary = "Giày đá bóng sai loại sân không chỉ ảnh hưởng hiệu suất mà còn dễ gây chấn thương.",
                            Title = "Hướng dẫn chọn giày đá bóng phù hợp với loại sân"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Category = "Bóng rổ",
                            Content = "Bóng rổ 3x3 chỉ cần 1 rổ, 3 người mỗi đội và sân nhỏ hơn. Trận đấu kéo dài 10 phút hoặc đội nào đạt 21 điểm trước sẽ thắng. Format này rất phù hợp cho sân bóng rổ đô thị.",
                            CreatedAt = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Slug = "bong-ro-3x3-xu-huong",
                            Summary = "Bóng rổ 3x3 đang thu hút đông đảo giới trẻ Việt Nam nhờ format nhanh, kịch tính và dễ tổ chức.",
                            Title = "Bóng rổ 3x3 — Xu hướng mới cho giới trẻ Việt"
                        });
                });

            modelBuilder.Entity("SanTheThao.Models.SportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SportTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sân bóng đá mini 5v5, 7v7",
                            Icon = "⚽",
                            IsActive = true,
                            Name = "Bóng đá"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sân cầu lông tiêu chuẩn",
                            Icon = "🏸",
                            IsActive = true,
                            Name = "Cầu lông"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sân bóng chuyền trong nhà",
                            Icon = "🏐",
                            IsActive = true,
                            Name = "Bóng chuyền"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sân bóng rổ 3v3 và 5v5",
                            Icon = "🏀",
                            IsActive = true,
                            Name = "Bóng rổ"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sân Pickleball tiêu chuẩn",
                            Icon = "🎾",
                            IsActive = true,
                            Name = "Pickleball"
                        });
                });

            modelBuilder.Entity("SanTheThao.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@santhethao.com",
                            FullName = "Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$43uD9/LEK4I160H3wmYi7urqfovNxCADfQxW03.5WDaxu1zQSwSMS",
                            PhoneNumber = "0900000000",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("SanTheThao.Models.Booking", b =>
                {
                    b.HasOne("SanTheThao.Models.Court", "Court")
                        .WithMany("Bookings")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SanTheThao.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SanTheThao.Models.Court", b =>
                {
                    b.HasOne("SanTheThao.Models.SportType", "SportType")
                        .WithMany("Courts")
                        .HasForeignKey("SportTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportType");
                });

            modelBuilder.Entity("SanTheThao.Models.NewsPost", b =>
                {
                    b.HasOne("SanTheThao.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("SanTheThao.Models.Court", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SanTheThao.Models.SportType", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("SanTheThao.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
