// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanTheThao.Data;

#nullable disable

namespace SanTheThao.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515093615_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SanTheThao.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SanTheThao.Models.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SportTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportTypeId");

                    b.ToTable("Courts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Bóng Đá A1",
                            PricePerHour = 200000m,
                            SportTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Bóng Đá A2",
                            PricePerHour = 200000m,
                            SportTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Bóng Đá B1",
                            PricePerHour = 250000m,
                            SportTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Cầu Lông 1",
                            PricePerHour = 80000m,
                            SportTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Cầu Lông 2",
                            PricePerHour = 80000m,
                            SportTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Bóng Chuyền 1",
                            PricePerHour = 150000m,
                            SportTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Bóng Rổ 1",
                            PricePerHour = 120000m,
                            SportTypeId = 4
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Bóng Rổ 2",
                            PricePerHour = 120000m,
                            SportTypeId = 4
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Pickleball 1",
                            PricePerHour = 100000m,
                            SportTypeId = 5
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            IsActive = true,
                            Name = "Sân Pickleball 2",
                            PricePerHour = 100000m,
                            SportTypeId = 5
                        });
                });

            modelBuilder.Entity("SanTheThao.Models.SportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SportTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sân bóng đá mini 5v5, 7v7",
                            Icon = "⚽",
                            IsActive = true,
                            Name = "Bóng đá"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sân cầu lông tiêu chuẩn",
                            Icon = "🏸",
                            IsActive = true,
                            Name = "Cầu lông"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sân bóng chuyền trong nhà",
                            Icon = "🏐",
                            IsActive = true,
                            Name = "Bóng chuyền"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sân bóng rổ 3v3 và 5v5",
                            Icon = "🏀",
                            IsActive = true,
                            Name = "Bóng rổ"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sân Pickleball tiêu chuẩn",
                            Icon = "🎾",
                            IsActive = true,
                            Name = "Pickleball"
                        });
                });

            modelBuilder.Entity("SanTheThao.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@santhethao.com",
                            FullName = "Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$zu5V9QqrV7bXMKbSe/TnFOIjuJRZdQ3qGl.Y2cUQiGJHDFJOt37FS",
                            PhoneNumber = "0900000000",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("SanTheThao.Models.Booking", b =>
                {
                    b.HasOne("SanTheThao.Models.Court", "Court")
                        .WithMany("Bookings")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SanTheThao.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SanTheThao.Models.Court", b =>
                {
                    b.HasOne("SanTheThao.Models.SportType", "SportType")
                        .WithMany("Courts")
                        .HasForeignKey("SportTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportType");
                });

            modelBuilder.Entity("SanTheThao.Models.Court", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SanTheThao.Models.SportType", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("SanTheThao.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
